///
/// ECL type definitions shared by the decoder and runtime
///

#pragma once

#include <cstddef>
#include <cstdint>

enum class EclOpcode : uint8_t {
  Setup = 0x00,
  End = 0x01,
  Jump = 0x02,
  Loop = 0x03,
  Call = 0x04,
  Return = 0x05,
  JumpHpGreater = 0x06,
  JumpHpLess = 0x07,
  JumpDifficulty = 0x08,
  JumpDirection = 0x09,
  JumpFrameGreater = 0x0a,
  JumpFrameLess = 0x0b,
  SetInterrupt = 0x0c,
  ClearInterrupt = 0x0d,

  Wait = 0x10,
  WaitScroll = 0x11,
  Move = 0x12,
  Rotate = 0x13,
  LinearRotate = 0x14,
  WaveX = 0x15,
  WaveY = 0x16,
  MoveX = 0x17,
  MoveY = 0x18,
  MoveXY = 0x19,
  MoveToPlayerX = 0x1a,
  MoveToPlayerY = 0x1b,
  MoveToPlayer = 0x1c,
  Accelerate = 0x1d,
  AccelerateTo = 0x1e,
  GravityBounce = 0x1f,

  SetAngle = 0x20,
  AddAngle = 0x21,
  RandomAngle = 0x22,
  AimAtPlayer = 0x23,
  SetSpeed = 0x24,
  AddSpeed = 0x25,
  SetPosition = 0x26,
  AddPosition = 0x27,
  RandomAngleUp = 0x28,
  RandomAngleDown = 0x29,
  SetSequenceAngle = 0x2a,
  MoveToPlayerPosition = 0x2b,
  RandomBoundedAngle = 0x2c,
  RandomPosition = 0x2d,
  MovePolar = 0x2e,

  FireBullet = 0x40,
  SetAutoFire = 0x41,
  SetBulletOffset = 0x42,
  SetBulletCommand = 0x43,
  SetBulletAngle = 0x44,
  AddBulletAngle = 0x45,
  SetBulletCount = 0x46,
  AddBulletCount = 0x47,
  SetBulletSpeed = 0x48,
  AddBulletSpeed = 0x49,
  SetBulletOption = 0x4a,
  SetBulletType = 0x4b,
  SetBulletColor = 0x4c,
  SetBulletAngularVelocity = 0x4d,
  SetBulletRepeat = 0x4e,
  AimBulletAtPlayer = 0x4f,
  SyncBulletAngle = 0x50,
  FireBulletUnscaled = 0x51,
  ClearBullets = 0x52,
  FireBulletLine = 0x53,
  BulletsToItems = 0x54,
  FireExtraBullet = 0x55,

  FireLaser = 0x60,
  SetLaserCommand = 0x61,
  SetLaserLength = 0x62,
  AddLaserLength = 0x63,
  SetLaserStartLength = 0x64,
  SetLaserAngle = 0x65,
  AddLaserAngle = 0x66,
  SetLaserCount = 0x67,
  AddLaserCount = 0x68,
  SetLaserSpeed = 0x69,
  AddLaserSpeed = 0x6a,
  SetLaserColor = 0x6b,
  SetLaserType = 0x6c,
  SetLaserWidth = 0x6d,
  AimLaserAtPlayer = 0x6e,
  SyncLaserAngle = 0x6f,
  SetLaserOffset = 0x70,
  FireLaserUnscaled = 0x71,

  SpawnLongLaser = 0x80,
  OpenLongLaser = 0x81,
  CloseLongLaser = 0x82,
  CloseLongLaserToLine = 0x83,
  AddLongLaserAngle = 0x84,
  FireHomingLaser = 0x85,

  EnableDraw = 0x90,
  DisableDraw = 0x91,
  EnableClip = 0x92,
  DisableClip = 0x93,
  EnableDamage = 0x94,
  DisableDamage = 0x95,
  EnablePlayerCollision = 0x96,
  DisablePlayerCollision = 0x97,
  EnableHorizontalMirror = 0x98,
  DisableHorizontalMirror = 0x99,

  SetAnimation = 0xa0,
  PlaySound = 0xa1,
  BossAction = 0xa2,
  SetSequenceAngleDelta = 0xa3,
  SpawnEnemy = 0xa4,
  SpawnEnemyWithAngle = 0xa5,
  SetHitbox = 0xa6,
  SetItem = 0xa7,
  Stage4Effect = 0xa8,
  SetDamageAnimation = 0xa9,
  BitLaser = 0xaa,
  BitAttack = 0xab,
  BitCommand = 0xac,
  SpawnBoss = 0xad,
  SpawnCircleEffect = 0xae,
  Stage3Effect = 0xaf,

  MoveValue = 0xb0,
  SetRegister = 0xb1,
  AddValue = 0xb2,
  SubtractValue = 0xb3,
  Sine = 0xb4,
  Cosine = 0xb5,
  Modulo = 0xb6,
  Random = 0xb7,
  CompareRegisters = 0xb8,
  CompareConstant = 0xb9,
  JumpGreater = 0xba,
  JumpLess = 0xbb,
  Increment = 0xbc,
  Decrement = 0xbd,
  JumpEqual = 0xbe,
};

enum class EclInterrupt : uint8_t {
  BossCount = 0,
  Hp = 1,
  Timer = 2,
  BitCount = 3,
};

enum class EclValue : uint8_t {
  Register0 = 0,
  Register1 = 1,
  Register2 = 2,
  Register3 = 3,
  Register4 = 4,
  Register5 = 5,
  Register6 = 6,
  Register7 = 7,

  LaserAngle = 128,
  LaserAngleDelta = 129,
  LaserCount = 130,
  LaserColor = 131,
  LaserLength = 132,
  LaserSpeed = 133,
  BulletAngle = 134,
  BulletAngleDelta = 135,
  BulletCount = 136,
  BulletRapidCount = 137,
  BulletSpeed = 138,
  BulletColor = 139,
  BulletAcceleration = 140,
  BulletRepeat = 141,
  BulletAngularVelocity = 142,
  ActorX = 143,
  ActorY = 144,
  ActorAngle = 145,
};

enum class EclBossAction : uint8_t {
  EnableSnake = 0,
  ButterflyWings = 1,
  BirdWings = 2,
  EnableFiveBits = 3,
  EnableSixBits = 4,
  BombShield = 5,
  BombSpirit = 6,
};

enum class EclBitCommand : uint8_t {
  ChangeSpeed = 1,
  SelectAttack = 2,
  ChangeRadius = 3,
  MoveTowardPlayer = 4,
};

enum class EclBitLaserCommand : uint8_t {
  Open = 0,
  Close = 1,
  CloseToLine = 2,
  Fixed = 3,
  Bidirectional = 4,
  Star = 5,
};

inline constexpr size_t kEclRegisterCount = 8;
inline constexpr size_t kEclInterruptCount = 4;
inline constexpr uint8_t kEclAllLongLasers = 0xff;

[[nodiscard]] constexpr bool IsEclRegister(EclValue value) {
  return static_cast<uint8_t>(value) < kEclRegisterCount;
}
