    TIME frame=0
    LOADFACE surf=0 file=0
    LOADFACE surf=1 file=1
    LOADFACE surf=2 file=6
    TIME frame=50
    MWOPEN
    FACE id=0
    TIME frame=70
    MSGREF id=@stage5_msg_000
    TIME frame=190
    MWCLOSE
    TIME frame=240
    MWOPEN
    FACE id=6
    TIME frame=260
    MSGREF id=@stage5_msg_001
    TIME frame=380
    NPG
    FACE id=2
    TIME frame=400
    MSGREF id=@stage5_msg_002
    TIME frame=520
    NPG
    FACE id=6
    TIME frame=540
    MSGREF id=@stage5_msg_003
    TIME frame=660
    NPG
    FACE id=0
    TIME frame=680
    MSGREF id=@stage5_msg_004
    TIME frame=800
    NPG
    FACE id=6
    TIME frame=820
    MSGREF id=@stage5_msg_005
    TIME frame=940
    MWCLOSE
    TIME frame=980
    MUSIC id=9
    TIME frame=1080
    ENEMY x=419 y=0 id=3
    TIME frame=1120
    ENEMY x=128 y=139 id=5
    TIME frame=1130
    ENEMY x=128 y=139 id=5
    TIME frame=1140
    ENEMY x=128 y=139 id=5
    TIME frame=1150
    ENEMY x=128 y=139 id=5
    TIME frame=1160
    ENEMY x=128 y=139 id=5
    TIME frame=1170
    ENEMY x=128 y=139 id=5
    TIME frame=1180
    ENEMY x=128 y=139 id=5
    TIME frame=1190
    ENEMY x=128 y=139 id=5
    TIME frame=1200
    ENEMY x=128 y=139 id=5
    TIME frame=1210
    ENEMY x=128 y=139 id=5
    TIME frame=1220
    ENEMY x=128 y=139 id=5
    TIME frame=1230
    ENEMY x=128 y=139 id=5
    TIME frame=1240
    ENEMY x=128 y=139 id=5
    TIME frame=1250
    ENEMY x=128 y=139 id=5
    TIME frame=1260
    ENEMY x=128 y=139 id=5
    TIME frame=1270
    ENEMY x=128 y=139 id=5
    TIME frame=1350
    ENEMY x=319 y=32 id=0
    TIME frame=1380
    ENEMY x=349 y=32 id=0
    ENEMY x=289 y=32 id=0
    TIME frame=1410
    ENEMY x=379 y=32 id=0
    ENEMY x=259 y=32 id=0
    TIME frame=1440
    ENEMY x=409 y=32 id=0
    ENEMY x=229 y=32 id=0
    TIME frame=1470
    ENEMY x=439 y=32 id=0
    ENEMY x=199 y=32 id=0
    TIME frame=1500
    ENEMY x=469 y=32 id=0
    ENEMY x=169 y=32 id=0
    TIME frame=1530
    ENEMY x=499 y=32 id=0
    ENEMY x=139 y=32 id=0
    TIME frame=1560
    ENEMY x=529 y=32 id=0
    ENEMY x=109 y=32 id=0
    TIME frame=1660
    ENEMY x=219 y=0 id=3
    ENEMY x=419 y=0 id=3
    TIME frame=1740
    ENEMY x=160 y=209 id=0
    ENEMY x=479 y=209 id=0
    TIME frame=1770
    ENEMY x=160 y=179 id=0
    ENEMY x=479 y=179 id=0
    TIME frame=1800
    ENEMY x=160 y=149 id=0
    ENEMY x=479 y=149 id=0
    TIME frame=1830
    ENEMY x=160 y=119 id=0
    ENEMY x=479 y=119 id=0
    TIME frame=1860
    ENEMY x=160 y=89 id=0
    ENEMY x=479 y=89 id=0
    TIME frame=1890
    ENEMY x=160 y=59 id=0
    ENEMY x=479 y=59 id=0
    TIME frame=1920
    ENEMY x=160 y=29 id=0
    ENEMY x=479 y=29 id=0
    TIME frame=1950
    ENEMY x=160 y=-1 id=0
    ENEMY x=479 y=-1 id=0
    TIME frame=1980
    ENEMY x=160 y=-31 id=0
    ENEMY x=479 y=-31 id=0
    TIME frame=2080
    ENEMY x=239 y=139 id=4
    ENEMY x=399 y=139 id=4
    TIME frame=2096
    ENEMY x=239 y=139 id=4
    ENEMY x=399 y=139 id=4
    TIME frame=2112
    ENEMY x=239 y=139 id=4
    ENEMY x=399 y=139 id=4
    TIME frame=2128
    ENEMY x=239 y=139 id=4
    ENEMY x=399 y=139 id=4
    TIME frame=2528
    BOSS x=319 y=-36 id=8
    WAITEX cond=0 opt=0
    TIME frame=2728
    EFC type=WARN
    TIME frame=2948
    EFC type=WARNSTOP
    TIME frame=2998
    MWOPEN
    FACE id=2
    TIME frame=3018
    MSGREF id=@stage5_msg_006
    TIME frame=3138
    NPG
    FACE id=12
    TIME frame=3158
    MSGREF id=@stage5_msg_007
    TIME frame=3278
    NPG
    FACE id=2
    TIME frame=3298
    MSGREF id=@stage5_msg_008
    TIME frame=3418
    NPG
    FACE id=12
    TIME frame=3438
    MSGREF id=@stage5_msg_009
    TIME frame=3558
    NPG
    FACE id=0
    TIME frame=3578
    MSGREF id=@stage5_msg_010
    TIME frame=3698
    NPG
    FACE id=12
    TIME frame=3718
    MSGREF id=@stage5_msg_011
    TIME frame=3838
    MWCLOSE
    MUSIC id=10
    BOSS x=319 y=-130 id=20
    WAITEX cond=0 opt=0
    TIME frame=3888
    MWOPEN
    NPG
    FACE id=0
    TIME frame=3908
    MSGREF id=@stage5_msg_012
    TIME frame=4028
    NPG
    FACE id=12
    TIME frame=4048
    MSGREF id=@stage5_msg_013
    TIME frame=4168
    NPG
    FACE id=0
    TIME frame=4188
    MSGREF id=@stage5_msg_014
    TIME frame=4308
    NPG
    FACE id=12
    TIME frame=4328
    MSGREF id=@stage5_msg_015
    TIME frame=4448
    NPG
    MSGREF id=@stage5_msg_016
    TIME frame=4568
    NPG
    MSGREF id=@stage5_msg_017
    TIME frame=4688
    NPG
    FACE id=2
    TIME frame=4708
    MSGREF id=@stage5_msg_018
    TIME frame=4828
    NPG
    FACE id=12
    TIME frame=4848
    MSGREF id=@stage5_msg_019
    TIME frame=4968
    NPG
    FACE id=0
    TIME frame=4988
    MSGREF id=@stage5_msg_020
    TIME frame=5048
    MSGREF id=@stage5_msg_021
    TIME frame=5168
    MWCLOSE
    EFC type=MUSICFADE
    EFC type=CFADEOUT
    TIME frame=5468
    STAGECLEAR
    END
