    TIME frame=0
    LOADFACE surf=0 file=0
    LOADFACE surf=1 file=1
    LOADFACE surf=2 file=2
    SSP speed=30
    TIME frame=50
    MWOPEN
    FACE id=0
    TIME frame=70
    MSGREF id=@stage1_msg_000
    TIME frame=310
    FACE id=2
    TIME frame=330
    NPG
    MSGREF id=@stage1_msg_001
    TIME frame=390
    MSGREF id=@stage1_msg_002
    TIME frame=590
    NPG
    FACE id=6
    TIME frame=630
    MSGREF id=@stage1_msg_003
    TIME frame=830
    NPG
    FACE id=2
    TIME frame=870
    MSGREF id=@stage1_msg_004
    TIME frame=1070
    NPG
    FACE id=6
    TIME frame=1110
    MSGREF id=@stage1_msg_005
    TIME frame=1310
    NPG
    FACE id=1
    TIME frame=1350
    MSGREF id=@stage1_msg_006
    TIME frame=1590
    MWCLOSE
    MUSIC id=1
    TIME frame=1700
    ENEMY x=138 y=0 id=2
    TIME frame=1712
    ENEMY x=138 y=0 id=2
    TIME frame=1724
    ENEMY x=138 y=0 id=2
    TIME frame=1736
    ENEMY x=138 y=0 id=2
    TIME frame=1748
    ENEMY x=138 y=0 id=2
    TIME frame=1760
    ENEMY x=138 y=0 id=2
    TIME frame=1772
    ENEMY x=138 y=0 id=2
    TIME frame=1784
    ENEMY x=138 y=0 id=2
    TIME frame=1796
    ENEMY x=138 y=0 id=2
    TIME frame=1808
    ENEMY x=138 y=0 id=2
    TIME frame=1820
    ENEMY x=501 y=0 id=2
    TIME frame=1832
    ENEMY x=501 y=0 id=2
    TIME frame=1844
    ENEMY x=501 y=0 id=2
    TIME frame=1856
    ENEMY x=501 y=0 id=2
    TIME frame=1868
    ENEMY x=501 y=0 id=2
    TIME frame=1880
    ENEMY x=501 y=0 id=2
    TIME frame=1892
    ENEMY x=501 y=0 id=2
    TIME frame=1904
    ENEMY x=501 y=0 id=2
    TIME frame=1916
    ENEMY x=501 y=0 id=2
    TIME frame=1928
    ENEMY x=501 y=0 id=2
    TIME frame=1988
    ENEMY x=264 y=0 id=3
    TIME frame=2000
    ENEMY x=264 y=0 id=3
    TIME frame=2012
    ENEMY x=264 y=0 id=3
    TIME frame=2024
    ENEMY x=264 y=0 id=3
    TIME frame=2036
    ENEMY x=264 y=0 id=3
    TIME frame=2048
    ENEMY x=264 y=0 id=3
    TIME frame=2060
    ENEMY x=374 y=0 id=3
    TIME frame=2072
    ENEMY x=374 y=0 id=3
    TIME frame=2084
    ENEMY x=374 y=0 id=3
    TIME frame=2096
    ENEMY x=374 y=0 id=3
    TIME frame=2108
    ENEMY x=374 y=0 id=3
    TIME frame=2120
    ENEMY x=374 y=0 id=3
    TIME frame=2132
    ENEMY x=289 y=0 id=3
    ENEMY x=374 y=0 id=3
    TIME frame=2144
    ENEMY x=289 y=0 id=3
    ENEMY x=374 y=0 id=3
    TIME frame=2156
    ENEMY x=289 y=0 id=3
    ENEMY x=374 y=0 id=3
    TIME frame=2168
    ENEMY x=289 y=0 id=3
    ENEMY x=374 y=0 id=3
    TIME frame=2180
    ENEMY x=289 y=0 id=3
    ENEMY x=374 y=0 id=3
    ENEMY x=501 y=0 id=4
    TIME frame=2260
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2272
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2284
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2296
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2308
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2320
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2332
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2344
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2356
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2368
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2380
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2392
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2472
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2482
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2492
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2502
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2512
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2522
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    ENEMY x=138 y=0 id=4
    TIME frame=2532
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2542
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2552
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2562
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2572
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2582
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2682
    ENEMY x=228 y=0 id=5
    ENEMY x=258 y=0 id=5
    ENEMY x=288 y=0 id=5
    TIME frame=2742
    ENEMY x=228 y=0 id=5
    ENEMY x=258 y=0 id=5
    ENEMY x=288 y=0 id=5
    TIME frame=2842
    ENEMY x=411 y=0 id=5
    ENEMY x=381 y=0 id=5
    ENEMY x=351 y=0 id=5
    TIME frame=2902
    ENEMY x=411 y=0 id=5
    ENEMY x=381 y=0 id=5
    ENEMY x=351 y=0 id=5
    TIME frame=3002
    ENEMY x=138 y=0 id=5
    ENEMY x=168 y=0 id=5
    ENEMY x=198 y=0 id=5
    ENEMY x=228 y=0 id=5
    ENEMY x=258 y=0 id=5
    ENEMY x=288 y=0 id=5
    TIME frame=3062
    ENEMY x=138 y=0 id=5
    ENEMY x=168 y=0 id=5
    ENEMY x=198 y=0 id=5
    ENEMY x=228 y=0 id=5
    ENEMY x=258 y=0 id=5
    ENEMY x=288 y=0 id=5
    TIME frame=3162
    ENEMY x=501 y=0 id=5
    ENEMY x=471 y=0 id=5
    ENEMY x=441 y=0 id=5
    ENEMY x=411 y=0 id=5
    ENEMY x=381 y=0 id=5
    ENEMY x=351 y=0 id=5
    TIME frame=3222
    ENEMY x=501 y=0 id=5
    ENEMY x=471 y=0 id=5
    ENEMY x=441 y=0 id=5
    ENEMY x=411 y=0 id=5
    ENEMY x=381 y=0 id=5
    ENEMY x=351 y=0 id=5
    TIME frame=3372
    ENEMY x=148 y=0 id=6
    TIME frame=3522
    ENEMY x=319 y=0 id=6
    TIME frame=3672
    ENEMY x=491 y=0 id=6
    TIME frame=3822
    ENEMY x=319 y=0 id=6
    SSP speed=9
    TIME frame=3930
    BOSS x=319 y=-60 id=0
    TIME frame=4070
    ENEMY x=138 y=0 id=4
    TIME frame=4210
    ENEMY x=501 y=0 id=4
    TIME frame=4350
    ENEMY x=138 y=0 id=4
    TIME frame=4490
    ENEMY x=501 y=0 id=4
    TIME frame=4630
    ENEMY x=138 y=0 id=4
    TIME frame=4770
    ENEMY x=501 y=0 id=4
    TIME frame=4910
    ENEMY x=138 y=0 id=4
    TIME frame=5050
    ENEMY x=501 y=0 id=4
    TIME frame=5190
    ENEMY x=138 y=0 id=4
    TIME frame=5330
    ENEMY x=501 y=0 id=4
    TIME frame=5600
    SSP speed=30
    BOSSDEAD
    TIME frame=5700
    ENEMY x=501 y=0 id=5
    ENEMY x=471 y=0 id=5
    ENEMY x=441 y=0 id=5
    ENEMY x=411 y=0 id=5
    ENEMY x=381 y=0 id=5
    ENEMY x=351 y=0 id=5
    TIME frame=5760
    ENEMY x=501 y=0 id=5
    ENEMY x=471 y=0 id=5
    ENEMY x=441 y=0 id=5
    ENEMY x=411 y=0 id=5
    ENEMY x=381 y=0 id=5
    ENEMY x=351 y=0 id=5
    TIME frame=5890
    ENEMY x=138 y=0 id=5
    ENEMY x=168 y=0 id=5
    ENEMY x=198 y=0 id=5
    ENEMY x=228 y=0 id=5
    ENEMY x=258 y=0 id=5
    ENEMY x=288 y=0 id=5
    TIME frame=5950
    ENEMY x=138 y=0 id=5
    ENEMY x=168 y=0 id=5
    ENEMY x=198 y=0 id=5
    ENEMY x=228 y=0 id=5
    ENEMY x=258 y=0 id=5
    ENEMY x=288 y=0 id=5
    TIME frame=6100
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6110
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6120
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6130
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6140
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6150
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6160
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6170
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6180
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6190
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6200
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    ENEMY x=139 y=0 id=4
    TIME frame=6210
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6220
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6230
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6240
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6250
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6260
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6270
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6280
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6290
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6300
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    ENEMY x=499 y=0 id=4
    TIME frame=6310
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6320
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6330
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6340
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6350
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6360
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6370
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6380
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6390
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6400
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6410
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6420
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6430
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6440
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6450
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6460
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6470
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6480
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6490
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6500
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6680
    EFC type=WARN
    TIME frame=6900
    EFC type=WARNSTOP
    EFC type=MUSICFADE
    MWOPEN
    FACE id=12
    TIME frame=6920
    MSGREF id=@stage1_msg_007
    TIME frame=7120
    NPG
    FACE id=0
    TIME frame=7160
    MSGREF id=@stage1_msg_008
    TIME frame=7360
    NPG
    FACE id=13
    TIME frame=7400
    MSGREF id=@stage1_msg_009
    TIME frame=7600
    NPG
    FACE id=0
    TIME frame=7640
    MSGREF id=@stage1_msg_010
    TIME frame=7840
    NPG
    FACE id=13
    TIME frame=7880
    MSGREF id=@stage1_msg_011
    TIME frame=8080
    NPG
    FACE id=3
    TIME frame=8120
    MSGREF id=@stage1_msg_012
    TIME frame=8320
    NPG
    FACE id=12
    TIME frame=8360
    MSGREF id=@stage1_msg_013
    TIME frame=8600
    MWCLOSE
    MUSIC id=2
    BOSS x=319 y=-60 id=7
    WAITEX cond=0 opt=0
    TIME frame=8650
    MWOPEN
    FACE id=12
    TIME frame=8690
    MSGREF id=@stage1_msg_014
    TIME frame=8810
    MSGREF id=@stage1_msg_015
    TIME frame=8930
    NPG
    FACE id=1
    TIME frame=8970
    MSGREF id=@stage1_msg_016
    TIME frame=9150
    NPG
    FACE id=12
    TIME frame=9190
    MSGREF id=@stage1_msg_017
    TIME frame=9370
    MSGREF id=@stage1_msg_018
    TIME frame=9490
    NPG
    FACE id=0
    TIME frame=9530
    MSGREF id=@stage1_msg_019
    TIME frame=9650
    NPG
    FACE id=12
    TIME frame=9690
    MSGREF id=@stage1_msg_020
    TIME frame=9810
    NPG
    FACE id=6
    TIME frame=9850
    MSGREF id=@stage1_msg_021
    TIME frame=9970
    NPG
    FACE id=0
    TIME frame=10010
    MSGREF id=@stage1_msg_022
    TIME frame=10070
    NPG
    MSGREF id=@stage1_msg_023
    TIME frame=10190
    NPG
    FACE id=6
    TIME frame=10230
    MSGREF id=@stage1_msg_024
    TIME frame=10290
    NPG
    MSGREF id=@stage1_msg_025
    TIME frame=10310
    NPG
    MSGREF id=@stage1_msg_026
    TIME frame=10330
    NPG
    MSGREF id=@stage1_msg_027
    TIME frame=10410
    NPG
    MSGREF id=@stage1_msg_028
    TIME frame=10530
    NPG
    FACE id=4
    TIME frame=10570
    MSGREF id=@stage1_msg_029
    TIME frame=10630
    NPG
    MSGREF id=@stage1_msg_030
    TIME frame=10870
    MWCLOSE
    EFC type=MUSICFADE
    EFC type=CFADEOUT
    TIME frame=11170
    STAGECLEAR
    END
