    TIME frame=0
    TIME frame=60
    MUSIC id=18
    TIME frame=300
    NPG
    MSGREF id=@ending_msg_000
    TIME frame=660
    FACE id=2
    NPG
    MSGREF id=@ending_msg_001
    TIME frame=920
    FACE id=1
    NPG
    MSGREF id=@ending_msg_002
    TIME frame=1200
    FACE id=3
    NPG
    MSGREF id=@ending_msg_003
    TIME frame=1470
    NPG
    STAFF id=134
    TIME frame=1770
    EFC type=WARN
    TIME frame=1820
    STAFF id=128
    STAFF id=0
    FACE id=4
    NPG
    MSGREF id=@ending_msg_004
    TIME frame=2350
    NPG
    MSGREF id=@ending_msg_005
    STAFF id=130
    STAFF id=2
    STAFF id=1
    STAFF id=0
    STAFF id=5
    STAFF id=4
    MSGREF id=@ending_msg_006
    TIME frame=2860
    STAFF id=129
    STAFF id=1
    FACE id=0
    NPG
    MSGREF id=@ending_msg_007
    TIME frame=3380
    STAFF id=131
    STAFF id=2
    STAFF id=0
    TIME frame=3880
    STAFF id=132
    STAFF id=3
    STAFF id=4
    FACE id=5
    NPG
    MSGREF id=@ending_msg_008
    TIME frame=4370
    NPG
    MSGREF id=@ending_msg_009
    TIME frame=4790
    NPG
    MSGREF id=@ending_msg_010
    TIME frame=5030
    NPG
    MSGREF id=@ending_msg_011
    TIME frame=5158
    MSGREF id=@ending_msg_012
    TIME frame=5398
    NPG
    MSGREF id=@ending_msg_013
    TIME frame=5698
    END
