    TIME frame=0
    LOADFACE surf=0 file=0
    LOADFACE surf=1 file=1
    LOADFACE surf=2 file=2
    SSP speed=30
    TIME frame=50
    MWOPEN
    FACE id=0
    TIME frame=70
    MSG "[VIVIT]"
    MSG "  \xC5\xDC\xCD\xC8\xC8\xA5\xA3\xAC\xC5\xDC\xCD\xC8\xC8\xA5\xA1\xAB"
    MSG "  \xE0\xC5\xA3\xAC\xD6\xBB\xD2\xAA\xCF\xF2\xD7\xC5\xD5\xE2\xB8\xF6\xB7\xBD\xCF\xF2"
    MSG "  \xD2\xBB\xD6\xB1\xD7\xDF\xCF\xC2\xC8\xA5\xBE\xCDOK\xC0\xB2\xA1\xAB"
    TIME frame=310
    FACE id=2
    TIME frame=330
    NPG
    MSG "[VIVIT]"
    MSG "  \xE0\xC5\xA3\xBF\xBB\xFA\xD3\xB0\xC8\xB7\xC8\xCF\xA1\xAD\xA1\xAD"
    MSG "  \xBA\xC3\xCF\xF1\xCF\xF2\xD5\xE2\xB1\xDF\xC0\xB4\xC1\xCB\xA1\xAB\xA3\xA1"
    TIME frame=390
    MSG "  \xD6\xF7\xA3\xAC\xD6\xF7\xC8\xCB\xA1\xAB\xA3\xA1\xA3\xBF"
    TIME frame=590
    NPG
    FACE id=6
    TIME frame=630
    MSG "[\xD6\xF7\xC8\xCB]"
    MSG "  \xB0\xD1\xC4\xC7\xC8\xBA\xBC\xD2\xBB\xEF\xA1\xB0\xC7\xE5\xC9\xA8\xB8\xC9\xBE\xBB\xA1\xB1\xA3\xA1"
    TIME frame=830
    NPG
    FACE id=2
    TIME frame=870
    MSG "[VIVIT]"
    MSG "  \xC4\xFA\xA1\xA2\xC4\xFA\xB5\xC4\xD2\xE2\xCB\xBC\xCA\xC7\xA3\xBF"
    TIME frame=1070
    NPG
    FACE id=6
    TIME frame=1110
    MSG "[\xD6\xF7\xC8\xCB]"
    MSG "  \xBA\xC3\xC0\xB2\xA3\xAC\xBA\xC3\xC0\xB2\xA3\xAC"
    MSG "  \xBE\xCD\xCA\xC7\xB0\xD1\xC4\xC7\xC8\xBA\xBC\xD2\xBB\xEF\xC8\xAB\xCA\xD5\xCA\xB0\xB5\xF4\xA3\xA1"
    TIME frame=1310
    NPG
    FACE id=1
    TIME frame=1350
    MSG "[VIVIT]"
    MSG "  \xCA\xC7\xA1\xA2\xCA\xC7\xB5\xC4\xA3\xA1"
    MSG "  \xCB\xE4\xC8\xBB\xB2\xBB\xCC\xAB\xC7\xE5\xB3\xFE\xD4\xB5\xD3\xC9\xA3\xAC"
    MSG "  \xB5\xAB\xCA\xC7\xCE\xD2\xBB\xE1\xC5\xAC\xC1\xA6\xB5\xC4\xA1\xEF"
    TIME frame=1590
    MWCLOSE
    MUSIC id=1
    TIME frame=1700
    ENEMY x=138 y=0 id=2
    TIME frame=1712
    ENEMY x=138 y=0 id=2
    TIME frame=1724
    ENEMY x=138 y=0 id=2
    TIME frame=1736
    ENEMY x=138 y=0 id=2
    TIME frame=1748
    ENEMY x=138 y=0 id=2
    TIME frame=1760
    ENEMY x=138 y=0 id=2
    TIME frame=1772
    ENEMY x=138 y=0 id=2
    TIME frame=1784
    ENEMY x=138 y=0 id=2
    TIME frame=1796
    ENEMY x=138 y=0 id=2
    TIME frame=1808
    ENEMY x=138 y=0 id=2
    TIME frame=1820
    ENEMY x=501 y=0 id=2
    TIME frame=1832
    ENEMY x=501 y=0 id=2
    TIME frame=1844
    ENEMY x=501 y=0 id=2
    TIME frame=1856
    ENEMY x=501 y=0 id=2
    TIME frame=1868
    ENEMY x=501 y=0 id=2
    TIME frame=1880
    ENEMY x=501 y=0 id=2
    TIME frame=1892
    ENEMY x=501 y=0 id=2
    TIME frame=1904
    ENEMY x=501 y=0 id=2
    TIME frame=1916
    ENEMY x=501 y=0 id=2
    TIME frame=1928
    ENEMY x=501 y=0 id=2
    TIME frame=1988
    ENEMY x=264 y=0 id=3
    TIME frame=2000
    ENEMY x=264 y=0 id=3
    TIME frame=2012
    ENEMY x=264 y=0 id=3
    TIME frame=2024
    ENEMY x=264 y=0 id=3
    TIME frame=2036
    ENEMY x=264 y=0 id=3
    TIME frame=2048
    ENEMY x=264 y=0 id=3
    TIME frame=2060
    ENEMY x=374 y=0 id=3
    TIME frame=2072
    ENEMY x=374 y=0 id=3
    TIME frame=2084
    ENEMY x=374 y=0 id=3
    TIME frame=2096
    ENEMY x=374 y=0 id=3
    TIME frame=2108
    ENEMY x=374 y=0 id=3
    TIME frame=2120
    ENEMY x=374 y=0 id=3
    TIME frame=2132
    ENEMY x=289 y=0 id=3
    ENEMY x=374 y=0 id=3
    TIME frame=2144
    ENEMY x=289 y=0 id=3
    ENEMY x=374 y=0 id=3
    TIME frame=2156
    ENEMY x=289 y=0 id=3
    ENEMY x=374 y=0 id=3
    TIME frame=2168
    ENEMY x=289 y=0 id=3
    ENEMY x=374 y=0 id=3
    TIME frame=2180
    ENEMY x=289 y=0 id=3
    ENEMY x=374 y=0 id=3
    ENEMY x=501 y=0 id=4
    TIME frame=2260
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2272
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2284
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2296
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2308
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2320
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2332
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2344
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2356
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2368
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2380
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2392
    ENEMY x=209 y=0 id=2
    ENEMY x=164 y=0 id=2
    TIME frame=2472
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2482
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2492
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2502
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2512
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2522
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    ENEMY x=138 y=0 id=4
    TIME frame=2532
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2542
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2552
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2562
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2572
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2582
    ENEMY x=429 y=0 id=2
    ENEMY x=474 y=0 id=2
    TIME frame=2682
    ENEMY x=228 y=0 id=5
    ENEMY x=258 y=0 id=5
    ENEMY x=288 y=0 id=5
    TIME frame=2742
    ENEMY x=228 y=0 id=5
    ENEMY x=258 y=0 id=5
    ENEMY x=288 y=0 id=5
    TIME frame=2842
    ENEMY x=411 y=0 id=5
    ENEMY x=381 y=0 id=5
    ENEMY x=351 y=0 id=5
    TIME frame=2902
    ENEMY x=411 y=0 id=5
    ENEMY x=381 y=0 id=5
    ENEMY x=351 y=0 id=5
    TIME frame=3002
    ENEMY x=138 y=0 id=5
    ENEMY x=168 y=0 id=5
    ENEMY x=198 y=0 id=5
    ENEMY x=228 y=0 id=5
    ENEMY x=258 y=0 id=5
    ENEMY x=288 y=0 id=5
    TIME frame=3062
    ENEMY x=138 y=0 id=5
    ENEMY x=168 y=0 id=5
    ENEMY x=198 y=0 id=5
    ENEMY x=228 y=0 id=5
    ENEMY x=258 y=0 id=5
    ENEMY x=288 y=0 id=5
    TIME frame=3162
    ENEMY x=501 y=0 id=5
    ENEMY x=471 y=0 id=5
    ENEMY x=441 y=0 id=5
    ENEMY x=411 y=0 id=5
    ENEMY x=381 y=0 id=5
    ENEMY x=351 y=0 id=5
    TIME frame=3222
    ENEMY x=501 y=0 id=5
    ENEMY x=471 y=0 id=5
    ENEMY x=441 y=0 id=5
    ENEMY x=411 y=0 id=5
    ENEMY x=381 y=0 id=5
    ENEMY x=351 y=0 id=5
    TIME frame=3372
    ENEMY x=148 y=0 id=6
    TIME frame=3522
    ENEMY x=319 y=0 id=6
    TIME frame=3672
    ENEMY x=491 y=0 id=6
    TIME frame=3822
    ENEMY x=319 y=0 id=6
    SSP speed=9
    TIME frame=3930
    BOSS x=319 y=-60 id=0
    TIME frame=4070
    ENEMY x=138 y=0 id=4
    TIME frame=4210
    ENEMY x=501 y=0 id=4
    TIME frame=4350
    ENEMY x=138 y=0 id=4
    TIME frame=4490
    ENEMY x=501 y=0 id=4
    TIME frame=4630
    ENEMY x=138 y=0 id=4
    TIME frame=4770
    ENEMY x=501 y=0 id=4
    TIME frame=4910
    ENEMY x=138 y=0 id=4
    TIME frame=5050
    ENEMY x=501 y=0 id=4
    TIME frame=5190
    ENEMY x=138 y=0 id=4
    TIME frame=5330
    ENEMY x=501 y=0 id=4
    TIME frame=5600
    SSP speed=30
    BOSSDEAD
    TIME frame=5700
    ENEMY x=501 y=0 id=5
    ENEMY x=471 y=0 id=5
    ENEMY x=441 y=0 id=5
    ENEMY x=411 y=0 id=5
    ENEMY x=381 y=0 id=5
    ENEMY x=351 y=0 id=5
    TIME frame=5760
    ENEMY x=501 y=0 id=5
    ENEMY x=471 y=0 id=5
    ENEMY x=441 y=0 id=5
    ENEMY x=411 y=0 id=5
    ENEMY x=381 y=0 id=5
    ENEMY x=351 y=0 id=5
    TIME frame=5890
    ENEMY x=138 y=0 id=5
    ENEMY x=168 y=0 id=5
    ENEMY x=198 y=0 id=5
    ENEMY x=228 y=0 id=5
    ENEMY x=258 y=0 id=5
    ENEMY x=288 y=0 id=5
    TIME frame=5950
    ENEMY x=138 y=0 id=5
    ENEMY x=168 y=0 id=5
    ENEMY x=198 y=0 id=5
    ENEMY x=228 y=0 id=5
    ENEMY x=258 y=0 id=5
    ENEMY x=288 y=0 id=5
    TIME frame=6100
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6110
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6120
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6130
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6140
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6150
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6160
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6170
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6180
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6190
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6200
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    ENEMY x=139 y=0 id=4
    TIME frame=6210
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6220
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6230
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6240
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6250
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6260
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6270
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6280
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6290
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    TIME frame=6300
    ENEMY x=519 y=0 id=2
    ENEMY x=489 y=0 id=2
    ENEMY x=499 y=0 id=4
    TIME frame=6310
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6320
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6330
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6340
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6350
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6360
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6370
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6380
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6390
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6400
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6410
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6420
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6430
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6440
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6450
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6460
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6470
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6480
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6490
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6500
    ENEMY x=119 y=0 id=2
    ENEMY x=149 y=0 id=2
    TIME frame=6680
    EFC type=WARN
    TIME frame=6900
    EFC type=WARNSTOP
    EFC type=MUSICFADE
    MWOPEN
    FACE id=12
    TIME frame=6920
    MSG "[\xC3\xD7\xC0\xF2\xD1\xC7]"
    MSG "  \xC4\xE3\xBE\xCD\xCA\xC7\xB4\xAB\xCB\xB5\xD6\xD0\xC4\xC7\xB8\xF6\xA1\xAD\xA1\xAD"
    MSG "  \xCA\xC7\xC3\xB4\xA3\xAC\xD5\xE6\xD3\xD0\xD2\xE2\xCB\xBC\xA1\xA3"
    MSG "  \xCE\xD2\xC0\xB4\xCE\xAA\xCE\xD2\xB5\xC4\xB2\xBF\xCF\xC2\xB1\xA8\xB3\xF0\xC1\xCB\xA3\xA1"
    TIME frame=7120
    NPG
    FACE id=0
    TIME frame=7160
    MSG "[VIVIT]"
    MSG "  \xB0\xA1\xB0\xA1\xA3\xA1\xA3\xBF"
    MSG "  \xCD\xBB\xC8\xBB\xB9\xA5\xBB\xF7\xB9\xFD\xC0\xB4\xB5\xC4\xA3\xAC"
    MSG "  \xB2\xBB\xCA\xC7\xC4\xE3\xC3\xC7\xC3\xB4\xA3\xBF"
    TIME frame=7360
    NPG
    FACE id=13
    TIME frame=7400
    MSG "[\xC3\xD7\xC0\xF2\xD1\xC7]"
    MSG "  \xB9\xFE\xB9\xFE\xA3\xAC\xCE\xD2\xB2\xC5\xB2\xBB\xB9\xDC\xC4\xD8\xA3\xAC"
    MSG "  \xB7\xB4\xD5\xFD\xCE\xD2\xBB\xE1\xC8\xC3\xC4\xE3\xB6\xD4\xCE\xD2\xC3\xC7\xB3\xF6\xCA\xD6\xD5\xE2\xBC\xFE\xCA\xC2"
    MSG "  \xBA\xF3\xA1\xA4\xBB\xDA\xA1\xA4\xB5\xC4\xA1\xEF"
    TIME frame=7600
    NPG
    FACE id=0
    TIME frame=7640
    MSG "[VIVIT]"
    MSG "  \xB2\xBB\xB9\xDC\xC0\xB2\xA3\xA1"
    MSG "  \xCE\xD2\xD2\xAA\xB0\xB4\xD5\xD5\xD6\xF7\xC8\xCB\xB5\xC4\xC3\xFC\xC1\xEE\xA3\xAC"
    MSG "  \xBD\xAB\xC4\xE3\xC3\xC7\xC8\xAB\xB2\xBF\xC7\xE5\xB3\xFD\xB8\xC9\xBE\xBB\xA3\xA1"
    TIME frame=7840
    NPG
    FACE id=13
    TIME frame=7880
    MSG "[\xC3\xD7\xC0\xF2\xD1\xC7]"
    MSG "  \xB8\xF8\xCE\xD2\xB1\xD5\xD7\xEC\xA3\xA1"
    MSG "  \xC4\xE3\xD5\xE2\xB8\xF6\xC6\xC6\xC0\xC3\xC5\xAE\xC6\xCD\xD5\xBD\xCA\xBF\xA3\xA1"
    TIME frame=8080
    NPG
    FACE id=3
    TIME frame=8120
    MSG "[VIVIT]"
    MSG "  \xC6\xC6\xA1\xA2\xC6\xC6\xC0\xC3\xA3\xA1\xA3\xBF"
    MSG "  \xB1\xF0\xBF\xAA\xCD\xE6\xD0\xA6\xC1\xCB\xA3\xA1"
    MSG "  \xC4\xE3\xB8\xF6\xB3\xF4\xA1\xA4\xC0\xCF\xA1\xA4\xCC\xAB\xA1\xA4\xC6\xC5\xA1\xAB"
    TIME frame=8320
    NPG
    FACE id=12
    TIME frame=8360
    MSG "[\xC3\xD7\xC0\xF2\xD1\xC7]"
    MSG "  \xB7\xC5\xC2\xED\xB9\xFD\xC0\xB4\xB0\xC9\xA3\xA1"
    TIME frame=8600
    MWCLOSE
    MUSIC id=2
    BOSS x=319 y=-60 id=7
    WAITEX cond=0 opt=0
    TIME frame=8650
    MWOPEN
    FACE id=12
    TIME frame=8690
    MSG "[\xC3\xD7\xC0\xF2\xD1\xC7]"
    MSG "  \xB0\xA1\xB0\xA1\xA3\xAC\xCE\xD2\xB5\xC4sylph\xB1\xBB\xA1\xAD\xA1\xAD"
    TIME frame=8810
    MSG "  \xB2\xBB\xD2\xAA\xD2\xF2\xCE\xAA\xB0\xD1\xCE\xD2\xBB\xF7\xB0\xDC\xC1\xCB"
    MSG "  \xBE\xCD\xC8\xCF\xCE\xAA\xD7\xD4\xBC\xBA\xBA\xDC\xC1\xCB\xB2\xBB\xC6\xF0\xC1\xCB\xA3\xA1"
    TIME frame=8930
    NPG
    FACE id=1
    TIME frame=8970
    MSG "[VIVIT]"
    MSG "  \xBB\xB0\xCB\xB5\xBB\xD8\xC0\xB4\xA3\xAC"
    MSG "  \xC4\xE3\xB5\xBD\xB5\xD7\xCA\xC7\xBA\xCE\xD0\xED\xC8\xCB\xB0\xA1\xA3\xBF"
    TIME frame=9150
    NPG
    FACE id=12
    TIME frame=9190
    MSG "[\xC3\xD7\xC0\xF2\xD1\xC7]"
    MSG "  \xB9\xFE\xB9\xFE\xA3\xAC"
    MSG "  \xB2\xC5\xB2\xBB\xBB\xE1\xB8\xE6\xCB\xDF\xC4\xE3\xC4\xD8\xA3\xAC"
    TIME frame=9370
    MSG "  \xC6\xC6\xC0\xC3\xA1\xA4\xC5\xAE\xC6\xCD\xA1\xA4\xD5\xBD\xCA\xBF\xA3\xA1"
    TIME frame=9490
    NPG
    FACE id=0
    TIME frame=9530
    MSG "[VIVIT]"
    MSG "  \xD5\xE6\xCA\xC7\xB5\xC4\xA3\xAC\xB6\xBC\xB6\xE0\xB4\xF3\xCB\xEA\xCA\xFD\xC1\xCB\xA1\xAD\xA1\xAD"
    TIME frame=9650
    NPG
    FACE id=12
    TIME frame=9690
    MSG "[\xC3\xD7\xC0\xF2\xD1\xC7]"
    MSG "  \xBA\xC3\xB9\xFD\xB7\xD6\xB0\xA1\xB0\xA1\xB0\xA1\xB0\xA1\xA1\xAB"
    TIME frame=9810
    NPG
    FACE id=6
    TIME frame=9850
    MSG "[\xD6\xF7\xC8\xCB]"
    MSG "  \xA3\xD6\xA3\xC9\xA3\xD6\xA1\xAD\xA1\xAD"
    MSG "  \xD4\xF5\xC3\xB4\xCB\xB5\xBB\xB0\xC4\xD8\xA3\xA1"
    TIME frame=9970
    NPG
    FACE id=0
    TIME frame=10010
    MSG "[VIVIT]"
    MSG "  \xB0\xA1\xCE\xD8\xA1\xA3"
    TIME frame=10070
    NPG
    MSG "[VIVIT]"
    MSG "  \xB0\xA1\xCE\xD8\xA3\xAC\xB6\xD4\xB2\xBB\xC6\xF0\xA1\xA3"
    TIME frame=10190
    NPG
    FACE id=6
    TIME frame=10230
    MSG "[\xD6\xF7\xC8\xCB]"
    MSG "  \xA3\xD6\xA3\xC9\xA3\xD6\xA3\xAC\xD5\xE2\xBC\xFE\xB9\xA4\xD7\xF7\xBD\xE1\xCA\xF8\xBA\xF3\xA3\xAC"
    TIME frame=10290
    NPG
    MSG "[\xD6\xF7\xC8\xCB]"
    MSG "  \xA3\xD6\xA3\xC9\xA3\xD6\xA3\xAC\xD5\xE2\xBC\xFE\xB9\xA4\xD7\xF7\xBD\xE1\xCA\xF8\xBA\xF3\xA3\xAC"
    MSG "  \xD2\xAA\xA3\xAE\xA3\xAE\xA3\xAE"
    TIME frame=10310
    NPG
    MSG "[\xD6\xF7\xC8\xCB]"
    MSG "  \xA3\xD6\xA3\xC9\xA3\xD6\xA3\xAC\xD5\xE2\xBC\xFE\xB9\xA4\xD7\xF7\xBD\xE1\xCA\xF8\xBA\xF3\xA3\xAC"
    MSG "  \xD2\xAA\xB3\xCD\xA3\xAE\xA3\xAE\xA3\xAE"
    TIME frame=10330
    NPG
    MSG "[\xD6\xF7\xC8\xCB]"
    MSG "  \xA3\xD6\xA3\xC9\xA3\xD6\xA3\xAC\xD5\xE2\xBC\xFE\xB9\xA4\xD7\xF7\xBD\xE1\xCA\xF8\xBA\xF3\xA3\xAC"
    MSG "  \xD2\xAA\xB3\xCD\xB7\xA3\xA3\xAE\xA3\xAE\xA3\xAE"
    TIME frame=10410
    NPG
    MSG "[\xD6\xF7\xC8\xCB]"
    MSG "  \xA3\xD6\xA3\xC9\xA3\xD6\xA3\xAC\xD5\xE2\xBC\xFE\xB9\xA4\xD7\xF7\xBD\xE1\xCA\xF8\xBA\xF3\xA3\xAC"
    MSG "  \xD2\xAA\xB3\xCD\xB7\xA3\xC4\xE3\xA1\xA3"
    TIME frame=10530
    NPG
    FACE id=4
    TIME frame=10570
    MSG "[VIVIT]"
    MSG "  \xB0\xA1\xCE\xD8\xA1\xAD\xA1\xAD"
    TIME frame=10630
    NPG
    MSG "[VIVIT]"
    MSG "  \xB0\xA1\xCE\xD8\xA1\xAD\xA1\xAD\xD6\xF7\xC8\xCB\xA1\xAD\xA1\xAD"
    TIME frame=10870
    MWCLOSE
    EFC type=MUSICFADE
    EFC type=CFADEOUT
    TIME frame=11170
    STAGECLEAR
    END
