    TIME frame=0
    LOADFACE surf=0 file=0
    LOADFACE surf=1 file=1
    LOADFACE surf=2 file=6
    TIME frame=50
    MWOPEN
    FACE id=0
    TIME frame=70
    MSG "[VIVIT]"
    MSG "  \xD5\xE2\xC0\xEF\xCA\xC7\xA3\xBF"
    MSG "  \xD4\xDA\xBE\xB2\xD6\xB9\xCE\xC0\xD0\xC7\xB9\xEC\xB5\xC0\xC9\xCF\xD3\xD0\xD5\xE2\xD6\xD6\xB6\xAB\xCE\xF7\xA1\xAD\xA1\xAD"
    MSG "  \xCA\xB2\xC3\xB4\xCA\xB1\xBA\xF2\xBD\xA8\xB3\xC9\xB5\xC4\xB0\xA1\xA1\xAD\xA1\xAD\xA3\xBF"
    TIME frame=190
    MWCLOSE
    TIME frame=240
    MWOPEN
    FACE id=6
    TIME frame=260
    MSG "[\xD6\xF7\xC8\xCB]"
    MSG "  \xB0\xA1\xB0\xA1\xA3\xAC\xCC\xAB\xBA\xC3\xC1\xCB\xA1\xAD\xA1\xAD\xCC\xAB\xBA\xC3\xC1\xCB\xA1\xA3"
    MSG "  \xC4\xDC\xB9\xBB\xC0\xB4\xB5\xBD\xD5\xE2\xD2\xBB\xB2\xBD\xA1\xA3"
    MSG "  \xC0\xB4\xB0\xC9\xA3\xAC\xD4\xD9\xD7\xEE\xBA\xF3\xC5\xAC\xC1\xA6\xD2\xBB\xB0\xD1\xA3\xA1"
    TIME frame=380
    NPG
    FACE id=2
    TIME frame=400
    MSG "[VIVIT]"
    MSG "  \xB0\xA5\xA3\xBF"
    TIME frame=520
    NPG
    FACE id=6
    TIME frame=540
    MSG "[\xD6\xF7\xC8\xCB]"
    MSG "  \xB7\xC5\xD0\xC4\xB0\xC9\xA1\xA3"
    MSG "  \xD4\xDA\xD5\xE2\xC0\xEF\xC3\xE6\xD3\xD0\xC4\xE3\xA3\xAC\xBB\xB9\xD3\xD0\xCE\xD2"
    MSG "  \xCB\xF9\xD7\xB7\xD1\xB0\xB5\xC4\xB6\xAB\xCE\xF7\xD4\xDA\xA1\xA3"
    TIME frame=660
    NPG
    FACE id=0
    TIME frame=680
    MSG "[VIVIT]"
    MSG "  \xD6\xF7\xC8\xCB\xA3\xAC\xD5\xE2\xB2\xBB\xCA\xC7\xA1\xAD\xA1\xAD"
    MSG "  \xD5\xE2\xB2\xBB\xCA\xC7\xBC\xF2\xB5\xA5\xB5\xC4\xA1\xAD\xA1\xAD\xC5\xDC\xCD\xC8\xB0\xA1\xA3\xA1"
    TIME frame=800
    NPG
    FACE id=6
    TIME frame=820
    MSG "[\xD6\xF7\xC8\xCB]"
    MSG "  \xC0\xB4\xB0\xC9\xA3\xA1"
    MSG "  \xBD\xAB\xC4\xE3\xA3\xA1\xBA\xCD\xCE\xD2\xB5\xC4\xA3\xA1\xCF\xA3\xCD\xFB\xA3\xA1"
    MSG "  \xCA\xD5\xC8\xEB\xCA\xD6\xD6\xD0\xA3\xA1\xA3\xA1"
    TIME frame=940
    MWCLOSE
    TIME frame=980
    MUSIC id=9
    TIME frame=1080
    ENEMY x=419 y=0 id=3
    TIME frame=1120
    ENEMY x=128 y=139 id=5
    TIME frame=1130
    ENEMY x=128 y=139 id=5
    TIME frame=1140
    ENEMY x=128 y=139 id=5
    TIME frame=1150
    ENEMY x=128 y=139 id=5
    TIME frame=1160
    ENEMY x=128 y=139 id=5
    TIME frame=1170
    ENEMY x=128 y=139 id=5
    TIME frame=1180
    ENEMY x=128 y=139 id=5
    TIME frame=1190
    ENEMY x=128 y=139 id=5
    TIME frame=1200
    ENEMY x=128 y=139 id=5
    TIME frame=1210
    ENEMY x=128 y=139 id=5
    TIME frame=1220
    ENEMY x=128 y=139 id=5
    TIME frame=1230
    ENEMY x=128 y=139 id=5
    TIME frame=1240
    ENEMY x=128 y=139 id=5
    TIME frame=1250
    ENEMY x=128 y=139 id=5
    TIME frame=1260
    ENEMY x=128 y=139 id=5
    TIME frame=1270
    ENEMY x=128 y=139 id=5
    TIME frame=1350
    ENEMY x=319 y=32 id=0
    TIME frame=1380
    ENEMY x=349 y=32 id=0
    ENEMY x=289 y=32 id=0
    TIME frame=1410
    ENEMY x=379 y=32 id=0
    ENEMY x=259 y=32 id=0
    TIME frame=1440
    ENEMY x=409 y=32 id=0
    ENEMY x=229 y=32 id=0
    TIME frame=1470
    ENEMY x=439 y=32 id=0
    ENEMY x=199 y=32 id=0
    TIME frame=1500
    ENEMY x=469 y=32 id=0
    ENEMY x=169 y=32 id=0
    TIME frame=1530
    ENEMY x=499 y=32 id=0
    ENEMY x=139 y=32 id=0
    TIME frame=1560
    ENEMY x=529 y=32 id=0
    ENEMY x=109 y=32 id=0
    TIME frame=1660
    ENEMY x=219 y=0 id=3
    ENEMY x=419 y=0 id=3
    TIME frame=1740
    ENEMY x=160 y=209 id=0
    ENEMY x=479 y=209 id=0
    TIME frame=1770
    ENEMY x=160 y=179 id=0
    ENEMY x=479 y=179 id=0
    TIME frame=1800
    ENEMY x=160 y=149 id=0
    ENEMY x=479 y=149 id=0
    TIME frame=1830
    ENEMY x=160 y=119 id=0
    ENEMY x=479 y=119 id=0
    TIME frame=1860
    ENEMY x=160 y=89 id=0
    ENEMY x=479 y=89 id=0
    TIME frame=1890
    ENEMY x=160 y=59 id=0
    ENEMY x=479 y=59 id=0
    TIME frame=1920
    ENEMY x=160 y=29 id=0
    ENEMY x=479 y=29 id=0
    TIME frame=1950
    ENEMY x=160 y=-1 id=0
    ENEMY x=479 y=-1 id=0
    TIME frame=1980
    ENEMY x=160 y=-31 id=0
    ENEMY x=479 y=-31 id=0
    TIME frame=2080
    ENEMY x=239 y=139 id=4
    ENEMY x=399 y=139 id=4
    TIME frame=2096
    ENEMY x=239 y=139 id=4
    ENEMY x=399 y=139 id=4
    TIME frame=2112
    ENEMY x=239 y=139 id=4
    ENEMY x=399 y=139 id=4
    TIME frame=2128
    ENEMY x=239 y=139 id=4
    ENEMY x=399 y=139 id=4
    TIME frame=2528
    BOSS x=319 y=-36 id=8
    WAITEX cond=0 opt=0
    TIME frame=2728
    EFC type=WARN
    TIME frame=2948
    EFC type=WARNSTOP
    TIME frame=2998
    MWOPEN
    FACE id=2
    TIME frame=3018
    MSG "[VIVIT]"
    MSG "  \xD4\xF5\xC3\xB4\xBB\xD8\xCA\xC2\xA1\xAD\xA1\xAD\xD5\xE2\xD6\xD6\xC6\xF8\xB7\xD5\xA3\xBF"
    MSG "  \xCA\xC7\xB4\xD3\xC3\xBB\xD3\xD0\xCC\xE5\xD1\xE9\xB9\xFD\xB5\xC4\xA1\xAD\xA1\xAD"
    MSG "  \xA1\xAD\xA1\xAD\xBF\xD6\xB2\xC0\xA1\xA3"
    TIME frame=3138
    NPG
    FACE id=12
    TIME frame=3158
    MSG "[\xB0\xAC\xC0\xFB\xCE\xF7]"
    MSG "  \xA3\xD6\xA3\xC9\xA3\xD6\xA1\xA2\xCE\xD2\xC0\xB4\xB8\xE6\xCB\xDF\xC4\xE3\xD2\xBB\xC7\xD0\xB0\xC9\xA1\xA3"
    MSG "  \xCA\xC7\xB5\xC4\xA3\xAC\xD2\xBB\xC7\xD0\xB6\xBC\xCA\xC7\xCE\xD2\xB5\xC4\xBE\xE7\xB1\xBE\xA1\xA3"
    MSG "  \xCE\xD2\xB5\xC4\xA1\xAD\xA1\xAD  "
    TIME frame=3278
    NPG
    FACE id=2
    TIME frame=3298
    MSG "[VIVIT]"
    MSG "  \xC4\xE3\xCA\xC7\xA3\xBF"
    TIME frame=3418
    NPG
    FACE id=12
    TIME frame=3438
    MSG "[\xB0\xAC\xC0\xFB\xCE\xF7]"
    MSG "  \xBB\xB9\xB2\xBB\xC3\xF7\xB0\xD7\xC3\xB4\xA3\xBF"
    MSG "  \xD3\xA6\xB8\xC3\xB6\xD4\xCE\xD2\xB5\xC4\xC9\xF9\xD2\xF4\xD3\xD0\xD3\xA1\xCF\xF3\xB0\xC9\xA3\xBF"
    TIME frame=3558
    NPG
    FACE id=0
    TIME frame=3578
    MSG "[VIVIT]"
    MSG "  \xC4\xE3\xA1\xAD\xC4\xE3\xCA\xC7\xA1\xAD\xA1\xAD\xA3\xA1\xA3\xA1"
    MSG "  \xD6\xF7\xC8\xCB\xA3\xA1\xA3\xA1"
    TIME frame=3698
    NPG
    FACE id=12
    TIME frame=3718
    MSG "[\xB0\xAC\xC0\xFB\xCE\xF7]"
    MSG "  \xA3\xD6\xA3\xC9\xA3\xD6\xA1\xAD\xA1\xAD"
    MSG "  \xBD\xAB\xCE\xD2\xA1\xAD\xA1\xAD\xB3\xAC\xD4\xBD\xB0\xC9\xA3\xA1"
    TIME frame=3838
    MWCLOSE
    MUSIC id=10
    BOSS x=319 y=-130 id=20
    WAITEX cond=0 opt=0
    TIME frame=3888
    MWOPEN
    NPG
    FACE id=0
    TIME frame=3908
    MSG "[VIVIT]"
    MSG "  \xD6\xF7\xC8\xCB\xA1\xAD\xA1\xAD"
    MSG "  \xD5\xE2\xCA\xC7\xD4\xF5\xC3\xB4\xBB\xD8\xCA\xC2\xA3\xBF"
    TIME frame=4028
    NPG
    FACE id=12
    TIME frame=4048
    MSG "[\xB0\xAC\xC0\xFB\xCE\xF7]"
    MSG "  \xCE\xD2\xD3\xD0\xD2\xBB\xB8\xF6\xC5\xAE\xB6\xF9\xA1\xA3"
    MSG "  \xCA\xFD\xCA\xAE\xC4\xEA\xC7\xB0\xD2\xF2\xCE\xAA\xD2\xBB\xB3\xA1\xD2\xE2\xCD\xE2\xA3\xAC"
    MSG "  \xB1\xBB\xB9\xD8\xD4\xDA\xD2\xEC\xBF\xD5\xBC\xE4\xC0\xEF\xC1\xCB\xA1\xA3"
    TIME frame=4168
    NPG
    FACE id=0
    TIME frame=4188
    MSG "[VIVIT]"
    MSG "  \xA1\xAD\xA1\xAD"
    TIME frame=4308
    NPG
    FACE id=12
    TIME frame=4328
    MSG "[\xB0\xAC\xC0\xFB\xCE\xF7]"
    MSG "  \xC4\xDC\xB9\xBB\xBD\xAB\xC5\xAE\xB6\xF9\xD5\xFC\xBE\xC8\xB3\xF6\xC0\xB4\xB5\xC4\xA3\xAC"
    MSG "  \xA3\xD6\xA3\xC9\xA3\xD6\xA3\xAC\xD6\xBB\xD3\xD0\xC4\xE3\xA1\xAD\xA1\xAD"
    TIME frame=4448
    NPG
    MSG "[\xB0\xAC\xC0\xFB\xCE\xF7]"
    MSG "  \xBD\xAB\xC3\xD7\xC0\xF2\xD1\xC7\xA1\xAD\xA1\xAD\xDA\xA4\xBA\xCD\xCE\xE8\xA1\xAD\xA1\xAD"
    MSG "  \xB8\xC7\xB4\xC4\xA1\xA2\xC2\xEA\xC0\xF6\xA1\xAD\xA1\xAD"
    TIME frame=4568
    NPG
    MSG "[\xB0\xAC\xC0\xFB\xCE\xF7]"
    MSG "\xBB\xB9\xD3\xD0\xCE\xD2\xB6\xBC\xBB\xF7\xB0\xDC\xC1\xCB\xB5\xC4\xC4\xE3\xA3\xAC"
    MSG "\xD2\xBB\xB6\xA8\xBF\xC9\xD2\xD4\xBE\xC8\xB3\xF6\xCE\xD2\xC5\xAE\xB6\xF9\xB5\xC4\xA1\xAD\xA1\xAD"
    TIME frame=4688
    NPG
    FACE id=2
    TIME frame=4708
    MSG "[VIVIT]"
    MSG "  \xD6\xF7\xA1\xAD\xC8\xCB\xA3\xBF\xA3\xBF"
    MSG "  \xD6\xF7\xC8\xCB\xA3\xA1\xA3\xA1"
    TIME frame=4828
    NPG
    FACE id=12
    TIME frame=4848
    MSG "[\xB0\xAC\xC0\xFB\xCE\xF7]"
    MSG "  \xCF\xD6\xD4\xDA\xD6\xBB\xD2\xAA\xCD\xF9\xC7\xB0\xBD\xF8\xA3\xA1\xA3\xA1"
    MSG "  \xD2\xF2\xCE\xAA\xD2\xBB\xC7\xD0\xB6\xBC\xD4\xDA\xC7\xB0\xB7\xBD\xA3\xA1"
    TIME frame=4968
    NPG
    FACE id=0
    TIME frame=4988
    MSG "[VIVIT]"
    MSG "  \xB0\xA1\xA1\xAD\xA1\xAD"
    MSG "  \xCA\xC7\xA3\xA1\xA3\xA1\xA3\xA1"
    TIME frame=5048
    MSG "  \xCE\xD2\xC3\xF7\xB0\xD7\xC1\xCB\xA3\xAC\xD6\xF7\xC8\xCB\xA3\xA1"
    TIME frame=5168
    MWCLOSE
    EFC type=MUSICFADE
    EFC type=CFADEOUT
    TIME frame=5468
    STAGECLEAR
    END
